import { parseModule } from "@llvm-analyzer/parser";
import { describe, expect, it } from "vitest";
import { collectFileReferenceCandidates } from "./file-references.ts";

describe("collectFileReferenceCandidates", () => {
  it("source_filename のファイル名を候補として抽出する", () => {
    const source = 'source_filename = "src/main.c"\n';
    const candidates = collectFileReferenceCandidates(parseModule(source).ast, source);

    expect(candidates).toEqual([
      {
        path: "src/main.c",
        range: {
          start: { offset: 19, line: 0, column: 19 },
          end: { offset: 29, line: 0, column: 29 },
        },
        source: "source_filename",
      },
    ]);
  });

  it("先頭コメントを飛ばして最初のトップレベル要素から抽出する", () => {
    const source = ["; generated by clang", 'source_filename = "src/main.c"'].join("\n");

    expect(
      collectFileReferenceCandidates(parseModule(source).ast, source).map(
        (candidate) => candidate.path,
      ),
    ).toEqual(["src/main.c"]);
  });

  it("DIFile の directory と filename を結合して候補として抽出する", () => {
    const source = [
      '!0 = distinct !DIFile(filename: "main.c", directory: "/workspace/src")',
      '!1 = !DIFile(filename: "/tmp/generated.c", directory: "/ignored")',
    ].join("\n");
    const candidates = collectFileReferenceCandidates(parseModule(source).ast, source);

    expect(candidates.map((candidate) => [candidate.path, candidate.source])).toEqual([
      ["/workspace/src/main.c", "debug-metadata"],
      ["/tmp/generated.c", "debug-metadata"],
    ]);
    expect(candidates[0]?.range).toEqual({
      start: { offset: 33, line: 0, column: 33 },
      end: { offset: 39, line: 0, column: 39 },
    });
  });

  it("複数行DIFileの文字列範囲を文書全体の位置へ変換する", () => {
    const source = [
      "!0 = !DIFile(",
      '  filename: "main.c",',
      '  directory: "/workspace/src"',
      ")",
    ].join("\n");

    expect(collectFileReferenceCandidates(parseModule(source).ast, source)[0]).toMatchObject({
      path: "/workspace/src/main.c",
      range: {
        start: { line: 1, column: 13 },
        end: { line: 1, column: 19 },
      },
    });
  });

  it("LLVM IR 文字列の 16 進エスケープを復号する", () => {
    const source = [
      'source_filename = "src\\2Fmain\\20file.c"',
      '!0 = !DIFile(filename: "nested\\5Cmain.c", directory: "debug\\20src")',
    ].join("\n");
    const candidates = collectFileReferenceCandidates(parseModule(source).ast, source);

    expect(candidates.map((candidate) => candidate.path)).toEqual([
      "src/main file.c",
      "debug src/nested\\main.c",
    ]);
  });

  it("filename 欠落・空文字・directory 欠落を安全に扱う", () => {
    const source = [
      'source_filename = ""',
      '!0 = !DIFile(directory: "/workspace")',
      '!1 = !DIFile(filename: "", directory: "/workspace")',
      '!2 = !DIFile(filename: "main.c")',
    ].join("\n");
    const candidates = collectFileReferenceCandidates(parseModule(source).ast, source);

    expect(candidates.map((candidate) => candidate.path)).toEqual(["main.c"]);
  });

  it("directory 末尾の slash と backslash を重複させずに結合する", () => {
    const source = [
      '!0 = !DIFile(filename: "main.c", directory: "/workspace/src/")',
      '!1 = !DIFile(filename: "main.c", directory: "C:\\5Cworkspace\\5Csrc\\5C")',
    ].join("\n");
    const candidates = collectFileReferenceCandidates(parseModule(source).ast, source);

    expect(candidates.map((candidate) => candidate.path)).toEqual([
      "/workspace/src/main.c",
      "C:\\workspace\\src\\main.c",
    ]);
  });

  it("quote と backslash escape を復号する", () => {
    const source = 'source_filename = "quoted\\22name\\\\tail.c"';
    const candidates = collectFileReferenceCandidates(parseModule(source).ast, source);

    expect(candidates.map((candidate) => candidate.path)).toEqual(['quoted"name\\tail.c']);
  });

  it("文字列がない source_filename と DIFile でないメタデータを無視する", () => {
    const source = ["source_filename =", "!0 = !{i32 1}", "@g = global i32 0"].join("\n");

    expect(collectFileReferenceCandidates(parseModule(source).ast, source)).toEqual([]);
  });

  it("未終端の source_filename 文字列は末尾までを候補範囲にする", () => {
    const source = 'source_filename = "unfinished.c';

    expect(collectFileReferenceCandidates(parseModule(source).ast, source)).toEqual([
      {
        path: "unfinished.c",
        range: {
          start: { offset: 19, line: 0, column: 19 },
          end: { offset: source.length, line: 0, column: source.length },
        },
        source: "source_filename",
      },
    ]);
  });
});
