import type { TokenKind } from "./token.ts";

/**
 * 命令オペコード。
 */
const OPCODES = [
  "ret",
  "br",
  "switch",
  "indirectbr",
  "invoke",
  "callbr",
  "resume",
  "catchswitch",
  "catchret",
  "cleanupret",
  "unreachable",
  "fneg",
  "add",
  "fadd",
  "sub",
  "fsub",
  "mul",
  "fmul",
  "udiv",
  "sdiv",
  "fdiv",
  "urem",
  "srem",
  "frem",
  "shl",
  "lshr",
  "ashr",
  "and",
  "or",
  "xor",
  "extractelement",
  "insertelement",
  "shufflevector",
  "extractvalue",
  "insertvalue",
  "alloca",
  "load",
  "store",
  "fence",
  "cmpxchg",
  "atomicrmw",
  "getelementptr",
  "trunc",
  "zext",
  "sext",
  "fptrunc",
  "fpext",
  "fptoui",
  "fptosi",
  "uitofp",
  "sitofp",
  "ptrtoint",
  "inttoptr",
  "ptrtoaddr",
  "bitcast",
  "addrspacecast",
  "icmp",
  "fcmp",
  "phi",
  "select",
  "freeze",
  "call",
  "va_arg",
  "landingpad",
  "catchpad",
  "cleanuppad",
] as const;

/**
 * 非整数の型キーワード。整数型 `i<N>` は {@link INTEGER_TYPE_PATTERN} で別途判定する。
 */
const TYPES = [
  "void",
  "half",
  "bfloat",
  "float",
  "double",
  "fp128",
  "x86_fp80",
  "ppc_fp128",
  "x86_mmx",
  "x86_amx",
  "label",
  "token",
  "metadata",
  "ptr",
  "opaque",
] as const;

/**
 * リテラル定数キーワード。
 */
const CONSTANTS = ["true", "false", "null", "none", "undef", "poison", "zeroinitializer"] as const;

/**
 * 構造キーワード・修飾子・呼出規約・各種フラグ・比較述語。
 * 命令でも型でも定数でもない予約語をまとめて `Keyword` として扱う。
 */
const KEYWORDS = [
  // 構造キーワード
  "define",
  "declare",
  "global",
  "constant",
  "alias",
  "ifunc",
  "module",
  "target",
  "source_filename",
  "datalayout",
  "triple",
  "attributes",
  "comdat",
  "uselistorder",
  "uselistorder_bb",
  "type",
  "to",
  "from",
  "within",
  "blockaddress",
  "addrspace",
  "section",
  "partition",
  "align",
  "alignstack",
  "gc",
  "prefix",
  "prologue",
  "personality",
  "asm",
  "sideeffect",
  "inteldialect",
  "distinct",
  "no_cfi",
  "any",
  "exactmatch",
  "largest",
  "noduplicates",
  "samesize",
  // 修飾子
  "private",
  "internal",
  "available_externally",
  "linkonce",
  "linkonce_odr",
  "weak",
  "weak_odr",
  "common",
  "appending",
  "extern_weak",
  "external",
  "dllimport",
  "dllexport",
  "default",
  "hidden",
  "protected",
  "dso_local",
  "dso_preemptable",
  "unnamed_addr",
  "local_unnamed_addr",
  "thread_local",
  "localdynamic",
  "initialexec",
  "localexec",
  "generaldynamic",
  "zeroext",
  "signext",
  "inreg",
  "byval",
  "byref",
  "preallocated",
  "inalloca",
  "sret",
  "elementtype",
  "noalias",
  "nocapture",
  "captures",
  "address",
  "address_is_null",
  "provenance",
  "read_provenance",
  "nofree",
  "nest",
  "returned",
  "nonnull",
  "dereferenceable",
  "dereferenceable_or_null",
  "writable",
  "initializes",
  "dead_on_unwind",
  "dead_on_return",
  "range",
  "nofpclass",
  "swiftself",
  "swiftasync",
  "swifterror",
  "immarg",
  "noundef",
  "allocalign",
  "allocptr",
  "readnone",
  "readonly",
  "writeonly",
  "nounwind",
  "noreturn",
  "willreturn",
  "cold",
  "hot",
  "noinline",
  "alwaysinline",
  "inlinehint",
  "optnone",
  "optsize",
  "minsize",
  "mustprogress",
  "nosync",
  "nocallback",
  "norecurse",
  "uwtable",
  "ssp",
  "sspreq",
  "sspstrong",
  "safestack",
  "shadowcallstack",
  "nobuiltin",
  "builtin",
  "convergent",
  "noimplicitfloat",
  "naked",
  "jumptable",
  "speculatable",
  "sanitize_address",
  "sanitize_thread",
  "sanitize_memory",
  "sanitize_hwaddress",
  "sanitize_memtag",
  "sanitize_realtime",
  "nonlazybind",
  "returns_twice",
  "argmemonly",
  "inaccessiblememonly",
  "inaccessiblemem_or_argmemonly",
  "memory",
  "argmem",
  "errnomem",
  "read",
  "write",
  "readwrite",
  "allockind",
  "allocsize",
  "frame_pointer",
  "null_pointer_is_valid",
  "strictfp",
  "denormal_fpenv",
  "ieee",
  "preserve-sign",
  "positive-zero",
  "dynamic",
  "vscale_range",
  "nooutline",
  "nocreateundeforpoison",
  "nocf_check",
  // 呼出規約
  "ccc",
  "fastcc",
  "coldcc",
  "ghccc",
  "cc",
  "webkit_jscc",
  "anyregcc",
  "preserve_mostcc",
  "preserve_allcc",
  "preserve_nonecc",
  "cxx_fast_tlscc",
  "tailcc",
  "swiftcc",
  "swifttailcc",
  "cfguard_checkcc",
  "x86_stdcallcc",
  "x86_fastcallcc",
  "x86_thiscallcc",
  "x86_vectorcallcc",
  "x86_regcallcc",
  "arm_apcscc",
  "arm_aapcscc",
  "arm_aapcs_vfpcc",
  "amdgpu_kernel",
  "amdgpu_cs",
  "amdgpu_vs",
  "amdgpu_ps",
  "spir_func",
  "spir_kernel",
  "ptx_kernel",
  "ptx_device",
  "win64cc",
  // フラグ
  "nsw",
  "nuw",
  "exact",
  "inbounds",
  "nneg",
  "disjoint",
  "samesign",
  "volatile",
  "atomic",
  "fast",
  "nnan",
  "ninf",
  "nsz",
  "arcp",
  "contract",
  "afn",
  "reassoc",
  "unordered",
  "monotonic",
  "acquire",
  "release",
  "acq_rel",
  "seq_cst",
  "syncscope",
  "tail",
  "musttail",
  "notail",
  // 比較述語
  "eq",
  "ne",
  "ugt",
  "uge",
  "ult",
  "ule",
  "sgt",
  "sge",
  "slt",
  "sle",
  "oeq",
  "ogt",
  "oge",
  "olt",
  "ole",
  "one",
  "ord",
  "ueq",
  "une",
  "uno",
] as const;

/**
 * バーワード → トークン種別の対応表。
 * 種別をまたぐ重複は無く、見つからなければ未分類 `Identifier` とする。
 */
const KEYWORD_KINDS: ReadonlyMap<string, TokenKind> = new Map<string, TokenKind>([
  ...OPCODES.map((w) => [w, "Opcode"] as const),
  ...TYPES.map((w) => [w, "Type"] as const),
  ...CONSTANTS.map((w) => [w, "Constant"] as const),
  ...KEYWORDS.map((w) => [w, "Keyword"] as const),
]);

/** 整数型 `i1`, `i32`, `i128` … の判定パターン。 */
const INTEGER_TYPE_PATTERN = /^i\d+$/;
/** byte type `b1`, `b32`, `b128` … の判定パターン。 */
const BYTE_TYPE_PATTERN = /^b\d+$/;

/**
 * バーワード（記号なしの語）を {@link TokenKind} に分類する。
 * 整数型 `i<N>` は `Type`、既知の予約語は対応する種別、それ以外は `Identifier`。
 *
 * @param word 分類対象の語（接頭辞を含まない）
 * @example
 * classifyBareword("i32") // "Type"
 * classifyBareword("add") // "Opcode"
 * classifyBareword("x")   // "Identifier"
 */
export const classifyBareword = (word: string): TokenKind => {
  if (INTEGER_TYPE_PATTERN.test(word)) return "Type";
  if (BYTE_TYPE_PATTERN.test(word)) return "Type";
  return KEYWORD_KINDS.get(word) ?? "Identifier";
};
