name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
      - uses: jetify-com/devbox-install-action@8c6a66ed6273138b1915457069de78cb52fe3bd7 # v0.15.0
        with:
          devbox-version: 0.17.5
      - run: devbox run -- pnpm install --frozen-lockfile
      - if: github.event_name == 'pull_request' && github.head_ref != 'changeset-release/main'
        run: devbox run -- pnpm changeset status --since=origin/main
      - run: devbox run -- pnpm lint
      - run: devbox run -- pnpm format
      - run: devbox run -- pnpm typecheck
      - run: devbox run -- pnpm test
      - run: devbox run -- pnpm build

  actions-pinned:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: jetify-com/devbox-install-action@8c6a66ed6273138b1915457069de78cb52fe3bd7 # v0.15.0
        with:
          devbox-version: 0.17.5
      - run: devbox run -- pinact run --check
